INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   rating,
                   vote_count,
                   description,
                   brand,
                   is_used)
VALUES ('Galaxy A24 6/128GB Black',
        'https://content.rozetka.com.ua/goods/images/big/328132324.jpg',
        'android',
        '11',
        6.5,
        '2340 x 1080',
        '50 Мп + 5 Мп + 2 Мп',
        13,
        'MediaTek Helio G99',
        8,
        6,
        195,
        5000,
        2,
        22000,
        4.9,
        724,
        'SAMSUNG',
        false);