INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Galaxy A24 6/128GB Black',
        'https://content.rozetka.com.ua/goods/images/big/328132324.jpg',
        'android',
        '11',
        6.5,
        '2340 x 1080',
        '50 Мп + 5 Мп + 2 Мп',
        13,
        'MediaTek Helio G99',
        8,
        6,
        195,
        5000,
        2,
        22000,
        'SAMSUNG',
        false);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Xiaomi Redmi Note 13 Pro+ 5G 12/512GB',
        'https://content2.rozetka.com.ua/goods/images/big/396635586.jpg',
        'android',
        '13',
        6.67,
        '2712x1220',
        '200 Мп + 8 Мп + 2 Мп',
        16,
        'MediaTek Dimensity 7200 Ultra',
        8,
        12,
        235,
        5000,
        2,
        18999,
        'SAMSUNG',
        false);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Apple iPhone 15 Pro 256GB',
        'https://content1.rozetka.com.ua/goods/images/big/364827123.jpg',
        'ios',
        '17',
        6.1,
        '2556x1179',
        '48 Мп + 12 Мп + 12 Мп',
        11,
        'Apple A17 Pro',
        6,
        12,
        184,
        4500,
        2,
        48499,
        'APPLE',
        false);