INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Galaxy A24 6/128GB Black',
        'https://content.rozetka.com.ua/goods/images/big/328132324.jpg',
        'android',
        '11',
        6.5,
        '2340 x 1080',
        '50 Мп + 5 Мп + 2 Мп',
        13,
        'MediaTek Helio G99',
        8,
        6,
        195,
        5000,
        2,
        22000,
        'SAMSUNG',
        false);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Xiaomi Redmi Note 13 Pro+ 5G 12/512GB',
        'https://content2.rozetka.com.ua/goods/images/big/396635586.jpg',
        'android',
        '13',
        6.67,
        '2712x1220',
        '200 Мп + 8 Мп + 2 Мп',
        16,
        'MediaTek Dimensity 7200 Ultra',
        8,
        12,
        235,
        5000,
        2,
        18999,
        'SAMSUNG',
        false);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Apple iPhone 15 Pro 256GB',
        'https://content1.rozetka.com.ua/goods/images/big/364827123.jpg',
        'ios',
        '17',
        6.1,
        '2556x1179',
        '48 Мп + 12 Мп + 12 Мп',
        11,
        'Apple A17 Pro',
        6,
        12,
        184,
        4500,
        2,
        48499,
        'APPLE',
        false);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Samsung Galaxy S20 Plus 128GB',
        'https://content.rozetka.com.ua/goods/images/big/427631418.jpg',
        'android',
        '10',
        6.7,
        '3200x1440',
        '64 Мп + 12 Мп + 12 Мп',
        10,
        'Exynos 990 5G',
        8,
        8,
        192,
        4500,
        2,
        9393,
        'SAMSUNG',
        true);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Samsung Galaxy S21 8/128GB',
        'https://content2.rozetka.com.ua/goods/images/big/409949029.jpg',
        'android',
        '10',
        6.2,
        '2040x1080',
        '64 Мп + 12 Мп + 12 Мп',
        10,
        'Qualcomm Snapdragon 888',
        8,
        8,
        192,
        4500,
        1,
        9500,
        'SAMSUNG',
        true);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Xiaomi Redmi Note 10 128GB',
        'https://content2.rozetka.com.ua/goods/images/big/429275179.jpg',
        'android',
        '11',
        6.43,
        '2400x1080',
        '48 Мп + 8 Мп + 2 Мп + 2 Мп',
        10,
        'Qualcomm Snapdragon 888',
        8,
        4,
        163,
        5000,
        2,
        5207,
        'XIAOMI',
        true);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Apple iPhone 12 128GB',
        'https://content1.rozetka.com.ua/goods/images/big/175435404.jpg',
        'ios',
        '11',
        6.1,
        '2532x1170',
        '12 Мп + 12 Мп',
        16,
        'Apple A14 Bionic',
        6,
        4,
        163,
        5000,
        2,
        23999,
        'APPLE',
        false);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Apple iPhone 11 128GB',
        'https://content.rozetka.com.ua/goods/images/big/37399220.jpg',
        'ios',
        '10',
        6.1,
        '1792x828',
        '12 Мп + 12 Мп',
        12,
        'Apple A13 Bionic',
        6,
        4,
        183,
        3046,
        2,
        21999,
        'APPLE',
        false);

INSERT INTO phone (model,
                   main_picture_URL,
                   operation_system,
                   os_verion,
                   screen_size,
                   resolution,
                   main_camera,
                   front_camera,
                   processor,
                   count_of_cores,
                   ram,
                   weight,
                   battary_capacity,
                   count_of_sim_card,
                   price,
                   brand,
                   is_used)
VALUES ('Samsung Galaxy S20FE 5G',
        'https://content1.rozetka.com.ua/goods/images/big/426939485.jpg',
        'android',
        '10',
        6.5,
        '2400 x 1080',
        '12 Мп + 12 Мп + 8 Мп',
        32,
        'Qualcomm Snapdragon 865',
        8,
        6,
        183,
        4500,
        1,
        9299,
        'APPLE',
        true);